# Generated by Django 3.0.5 on 2020-11-14 06:54

import dating.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=dating.models.UniqueImageField(null=True, upload_to='images'),
        ),
    ]
