# Generated by Django 3.0.5 on 2020-11-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='messages_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
