# Generated by Django 3.0.5 on 2020-11-29 03:13

import dating.models.User
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0006_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture_violated',
            field=models.BooleanField(default=False),
        ),
    ]
