from .index import *
from .login import *
from .index import *
from .login import *
from .register import *
from .logout import *
from .verify_email import *
from .edit import *
from .resend import *
from .password import *
from .chat import *
from .DiscoverView import *
from .UserView import *
from .ChatView import *
